export interface CategoryRule {
  id: string;
  keywordPatterns: RegExp[];
  choiceTemplates: { labels: string[]; threshold: number }[];
  choicePatterns: { pattern: RegExp; threshold: number }[];
}

export const ATTRIBUTE_RULES: CategoryRule[] = [
  {
    id: "gender",
    keywordPatterns: [/性別/, /ジェンダー/, /\bgender\b/i, /\bsex\b/i],
    choiceTemplates: [
      { labels: ["男性", "女性"], threshold: 0.5 },
      { labels: ["男", "女"], threshold: 0.5 },
      { labels: ["male", "female"], threshold: 0.5 },
      { labels: ["男性", "女性", "その他", "回答しない"], threshold: 0.5 },
      { labels: ["male", "female", "other", "prefer not to say"], threshold: 0.5 },
    ],
    choicePatterns: [],
  },
  {
    id: "age",
    keywordPatterns: [/年齢/, /年代/, /世代/, /\bage\b/i, /\bage\s*group\b/i, /\bgeneration\b/i],
    choiceTemplates: [
      {
        labels: ["10代", "20代", "30代", "40代", "50代", "60代", "70代以上"],
        threshold: 0.4,
      },
      {
        labels: ["10代以下", "20代", "30代", "40代", "50代", "60代以上"],
        threshold: 0.4,
      },
      {
        labels: ["under 18", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
        threshold: 0.4,
      },
    ],
    choicePatterns: [
      { pattern: /\d+\s*[~〜～―\-–]\s*\d+\s*歳/, threshold: 0.4 },
      { pattern: /\d+代/, threshold: 0.4 },
      { pattern: /\d+\s*[~〜～―\-–]\s*\d+\s*(years|yrs)/i, threshold: 0.4 },
      { pattern: /\bunder\s+\d+\b/i, threshold: 0.3 },
    ],
  },
  {
    id: "location",
    keywordPatterns: [
      /お住まい/,
      /都道府県/,
      /地域/,
      /出身/,
      /居住/,
      /\blocation\b/i,
      /\bregion\b/i,
      /\bresidence\b/i,
      /\bprefecture\b/i,
    ],
    choiceTemplates: [
      {
        labels: [
          "北海道",
          "青森県",
          "岩手県",
          "宮城県",
          "秋田県",
          "山形県",
          "福島県",
          "茨城県",
          "栃木県",
          "群馬県",
          "埼玉県",
          "千葉県",
          "東京都",
          "神奈川県",
          "新潟県",
          "富山県",
          "石川県",
          "福井県",
          "山梨県",
          "長野県",
          "岐阜県",
          "静岡県",
          "愛知県",
          "三重県",
          "滋賀県",
          "京都府",
          "大阪府",
          "兵庫県",
          "奈良県",
          "和歌山県",
          "鳥取県",
          "島根県",
          "岡山県",
          "広島県",
          "山口県",
          "徳島県",
          "香川県",
          "愛媛県",
          "高知県",
          "福岡県",
          "佐賀県",
          "長崎県",
          "熊本県",
          "大分県",
          "宮崎県",
          "鹿児島県",
          "沖縄県",
        ],
        threshold: 0.15,
      },
      {
        labels: ["北海道", "東北", "関東", "中部", "近畿", "中国", "四国", "九州", "沖縄"],
        threshold: 0.5,
      },
      {
        labels: [
          "北海道",
          "東北",
          "関東",
          "北陸・甲信越",
          "東海",
          "近畿",
          "中国・四国",
          "九州・沖縄",
        ],
        threshold: 0.5,
      },
    ],
    choicePatterns: [],
  },
  {
    id: "occupation",
    keywordPatterns: [/職業/, /職種/, /就業/, /\boccupation\b/i, /\bjob\b/i, /\bemployment\b/i],
    choiceTemplates: [
      {
        labels: [
          "会社員",
          "公務員",
          "自営業",
          "パート・アルバイト",
          "学生",
          "専業主婦・主夫",
          "無職",
        ],
        threshold: 0.4,
      },
      {
        labels: [
          "会社員（正社員）",
          "会社員（契約・派遣）",
          "公務員",
          "自営業・フリーランス",
          "パート・アルバイト",
          "学生",
          "主婦・主夫",
          "無職・退職",
          "その他",
        ],
        threshold: 0.3,
      },
      {
        labels: [
          "employed full-time",
          "employed part-time",
          "self-employed",
          "student",
          "retired",
          "unemployed",
        ],
        threshold: 0.4,
      },
    ],
    choicePatterns: [],
  },
  {
    id: "income",
    keywordPatterns: [/年収/, /収入/, /所得/, /\bincome\b/i, /\bsalary\b/i, /\bearnings\b/i],
    choiceTemplates: [],
    choicePatterns: [
      { pattern: /\d+万円/, threshold: 0.4 },
      { pattern: /[$￥¥]\s*\d+/i, threshold: 0.4 },
      { pattern: /\d+\s*[~〜～―\-–]\s*\d+\s*万/, threshold: 0.3 },
    ],
  },
  {
    id: "education",
    keywordPatterns: [/学歴/, /最終学歴/, /\beducation\b/i, /\bdegree\b/i],
    choiceTemplates: [
      {
        labels: ["中学校", "高校", "専門学校", "短大", "大学", "大学院"],
        threshold: 0.4,
      },
      {
        labels: ["中学校卒", "高校卒", "専門学校卒", "短大卒", "大学卒", "大学院卒"],
        threshold: 0.4,
      },
      {
        labels: [
          "high school",
          "associate degree",
          "bachelor's degree",
          "master's degree",
          "doctorate",
        ],
        threshold: 0.4,
      },
    ],
    choicePatterns: [],
  },
  {
    id: "marital_status",
    keywordPatterns: [
      /婚姻/,
      /結婚/,
      /未婚/,
      /既婚/,
      /配偶者/,
      /\bmarital\b/i,
      /\bmarried\b/i,
      /\brelationship\s*status\b/i,
    ],
    choiceTemplates: [
      { labels: ["未婚", "既婚"], threshold: 0.5 },
      { labels: ["未婚", "既婚", "離別", "死別"], threshold: 0.5 },
      { labels: ["single", "married", "divorced", "widowed"], threshold: 0.5 },
    ],
    choicePatterns: [],
  },
  {
    id: "household",
    keywordPatterns: [
      /世帯/,
      /家族構成/,
      /同居/,
      /子供の有無/,
      /子どもの有無/,
      /\bhousehold\b/i,
      /\bfamily\s*size\b/i,
      /\bchildren\b/i,
    ],
    choiceTemplates: [
      { labels: ["1人", "2人", "3人", "4人", "5人以上"], threshold: 0.5 },
      {
        labels: ["単身", "夫婦のみ", "夫婦と子供", "三世代同居", "その他"],
        threshold: 0.4,
      },
    ],
    choicePatterns: [{ pattern: /\d+人/, threshold: 0.5 }],
  },
  {
    id: "industry",
    keywordPatterns: [/業種/, /業界/, /\bindustry\b/i, /\bsector\b/i],
    choiceTemplates: [
      {
        labels: [
          "農林水産業",
          "建設業",
          "製造業",
          "情報通信業",
          "運輸業",
          "卸売・小売業",
          "金融・保険業",
          "不動産業",
          "サービス業",
          "医療・福祉",
          "教育",
          "公務",
        ],
        threshold: 0.3,
      },
    ],
    choicePatterns: [],
  },
  {
    id: "company_size",
    keywordPatterns: [
      /従業員数/,
      /企業規模/,
      /会社規模/,
      /社員数/,
      /\bcompany\s*size\b/i,
      /\bnumber\s*of\s*employees\b/i,
    ],
    choiceTemplates: [],
    choicePatterns: [
      { pattern: /\d+\s*[~〜～―\-–]\s*\d+\s*人/, threshold: 0.4 },
      { pattern: /\d+人(未満|以上|以下)/, threshold: 0.3 },
      { pattern: /\d+\s*[~〜～―\-–]\s*\d+\s*employees/i, threshold: 0.4 },
    ],
  },
];
