name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: Run benchmark
        run: BENCH_OUTPUT=bench/output.json vp run bench

      - name: Store benchmark result
        continue-on-error: true
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: bench/output.json
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: bench
          auto-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
