name: Release PR

on:
  push:
    branches: [develop]

jobs:
  release-pr:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: x-motemen/git-pr-release-action@v1
        with:
          base: main
          head: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
